// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2cnjoD-adcLXITY4qEWYnaaqIiBS-elY',
    appId: '1:421457527534:web:a6ad898f271095da6369ff',
    messagingSenderId: '421457527534',
    projectId: 'zae-fgv-coffee',
    authDomain: 'zae-fgv-coffee.firebaseapp.com',
    storageBucket: 'zae-fgv-coffee.appspot.com',
    measurementId: 'G-NQQM6LVTGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQ0uaR6XosNpPwrDTloDM5SoJnxF8ako',
    appId: '1:421457527534:android:8d95c18a87144a4c6369ff',
    messagingSenderId: '421457527534',
    projectId: 'zae-fgv-coffee',
    storageBucket: 'zae-fgv-coffee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrCgPPRrFzzLORT7DR8kRuLraprRlbmew',
    appId: '1:421457527534:ios:2f673f363ed96d8b6369ff',
    messagingSenderId: '421457527534',
    projectId: 'zae-fgv-coffee',
    storageBucket: 'zae-fgv-coffee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrCgPPRrFzzLORT7DR8kRuLraprRlbmew',
    appId: '1:421457527534:ios:2f673f363ed96d8b6369ff',
    messagingSenderId: '421457527534',
    projectId: 'zae-fgv-coffee',
    storageBucket: 'zae-fgv-coffee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2cnjoD-adcLXITY4qEWYnaaqIiBS-elY',
    appId: '1:421457527534:web:ac36ee4e801d0d0b6369ff',
    messagingSenderId: '421457527534',
    projectId: 'zae-fgv-coffee',
    authDomain: 'zae-fgv-coffee.firebaseapp.com',
    storageBucket: 'zae-fgv-coffee.appspot.com',
    measurementId: 'G-7CBF9LD4JC',
  );
}
