name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove esta linha se desejar publicar para o pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2

  # Removi o flutter_web_plugins a menos que seja estritamente necessário
  # flutter_web_plugins:
  #   sdk: flutter

  # Suas outras dependências
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.15
  connectivity_plus: ^6.0.5
  flutter_dotenv: ^5.0.0
  path: ^1.8.0
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  android_id: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Roboto-SemiBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
